services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # Novo padrão: mapear a pasta pai para evitar o erro de versão
      - postgresql_base:/var/lib/postgresql
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 55432:5432
    networks:
      - nw_northwind

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:5050
    networks:
      - nw_northwind

networks:
  nw_northwind:
    driver: bridge

volumes:
  postgresql_base:
  pgadmin_data: